VPATH = hdr/
obj=main.o input.o malloc_input.o snappend.o str_cmp.o sappend.o chr_str.o strcasecmp.o str_spn.o rev_str.o str_cmp.o palindrome.o squeeze.o insert_char.o
app:$(obj) 
	gcc -o app $(obj)

$(obj):header.h
clean:
	rm $(obj)

