app:main.o create_node.o insert_begin.o insert_after.o display.o input.o reverse_display.o delete_begin.o delete_end.o insert_pos.o insert_middle.o
	gcc -o app *.o
	mv *.o ../obj
main.o:main.c
	gcc -g -Wall -I ../hdr -c main.c
create_node.o:create_node.c
	gcc -g -Wall -I ../hdr -c create_node.c
insert_begin.o:insert_begin.c
	gcc -g -Wall -I ../hdr -c insert_begin.c
insert_after.o:insert_after.c
	gcc -g -Wall -I ../hdr -c insert_after.c
display.o:display.c
	gcc -g -Wall -I ../hdr -c display.c
input.o:input.c
	gcc -g -Wall -I ../hdr -c input.c
reverse_display.o:reverse_display.c
	gcc -g -Wall -I ../hdr -c reverse_display.c
delete_begin.o:delete_begin.c
	gcc -g -Wall -I ../hdr -c delete_begin.c
delete_end.o:delete_end.c
	gcc -g -Wall -I ../hdr -c delete_end.c
insert_pos.o:insert_pos.c
	gcc -g -Wall -I ../hdr -c insert_pos.c
insert_middle.o:insert_middle.c
	gcc -g -Wall -I ../hdr -c insert_middle.c

