.TH "src Directory Reference" 3 "Thu Sep 27 2018" "Version 0.19" "Implentation Of Cat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBheader\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBmain_wc\&.c\fP"
.br
.in -1c
