.TH "src/header.h" 3 "Thu Sep 27 2018" "Version 0.19" "Implentation Of Cat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUF\fP   256"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUF   256"

.SH "Author"
.PP 
Generated automatically by Doxygen for Implentation Of Cat from the source code\&.
