.TH "src/main_wc.c" 3 "Thu Sep 27 2018" "Version 0.19" "Implentation Of Cat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main_wc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
.nf
6 {
7     int i = 0;
8     int count = 0;
9     int line = 0;
10     int word = 0;
11     char ch;
12     char prev;
13     FILE *fp;
14     char *buf = NULL;
15     buf = ( char * ) malloc ( sizeof(char) * BUF );
16    // for ( i = 1; i < argc; i++) {
17     fp = fopen ( argv[1] , "r" );
18     if( fp == NULL ) {
19         printf( "File is not created");
20     }
21     else
22     {
23         while (  ( ch = fgetc ( fp ) ) != EOF ) {
24             
25             if ( ( ch == ' ' &&  prev != ' '  && prev != '\n'  && prev != '\t'  ) ) {
26               word++;
27               count++;
28            }
29            else if ( ch == '\n' ) {
30               line++;
31               count++;
32               word++;
33            }
34            else
35               count++;
36          prev = ch;
37         } 
38         fclose(fp);
39     }
40     printf ( " the characters are %d ", count);
41     printf ( " the lines are %d ", line);
42     printf ( " the words are %d ", word);
43     //}
44     
45     return 0;
46 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Implentation Of Cat from the source code\&.
