app:main.o input.o array_input.o display.o bubble_sort.o bin_search.o
	gcc -o app *.o
main.o:main.c
	gcc -Wall -c main.c
input.o:input.c
	gcc -Wall -c input.c
array_input.o:array_input.c
	gcc -Wall -c array_input.c
display.o:display.c
	gcc -Wall -c display.c
bubble_sort.o:bubble_sort.c
	gcc -Wall -c bubble_sort.c
bin_search.o:bin_search.c
	gcc -Wall -c bin_search.c
