app:main.o linear_search.o input.o array_input.o
	gcc -o app *.o
main.o:main.c
	gcc -Wall -c main.c
linear_search.o:linear_search.c
	gcc -Wall -c linear_search.c
input.o:input.c
	gcc -Wall -c input.c
array_input.o:array_input.c
	gcc -Wall -c array_input.c
