VPATH = ../hdr/
obj = main.o copy_bits.o left_rotate_n.o right_rotate.o assignment_4.o count_bits.o left_rotate.o swap_bits.o assignment_8.o dec_to_binary.o swap_external.o bits_copy.o invert.o right_rotate_n.o input.o read_input.o
app: $(obj)
	gcc -o app $(obj)
$(obj):header.h
clean:
	mv $(obj) ../obj
	rm *.o

		
		


