app: main.o display.o pop.o push.o input.o
	gcc -o app *.o
main.o:main.c
	gcc -g -Wall -I ../hdr -c main.c
display.o:display.c
	gcc -g -Wall -I ../hdr -c display.c
pop.o:pop.c
	gcc -g -Wall -I ../hdr -c pop.c
push.o:push.c
	gcc -g -Wall -I ../hdr -c push.c
input.o:input.c
	gcc -g -Wall -I ../hdr -c input.c
