app:main.o create_node.o insert_tree.o input.o display.o delete_node.o count_nodes.o
	gcc -o app *.o
	mv *.o ../obj
main.o:main.c
	gcc -g -Wall -I ../hdr -c main.c
create_node.o:create_node.c
	gcc -g -Wall -I ../hdr -c create_node.c
insert_tree.o:insert_tree.c
	gcc -g -Wall -I ../hdr -c insert_tree.c
input.o:input.c
	gcc -g -Wall -I ../hdr -c input.c
display.o:display.c
	gcc -g -Wall -I ../hdr -c display.c
delete_node.o:delete_node.c
	gcc -g -Wall -I ../hdr -c delete_node.c
count_nodes.o:count_nodes.c
	gcc -g -Wall -I ../hdr -c count_nodes.c

